2019-11-12 11:13:42,826 DEBUG 98114   ---  [MainThread] - [GET] -> [/cms/admin/authority] from:127.0.0.1 costs:9.000 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:13:43,086 DEBUG 98114   ---  [MainThread] - [DELETE] -> [/cms/admin/6] from:127.0.0.1 costs:2.590 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:13:43,185 DEBUG 98114   ---  [MainThread] - [GET] -> [/cms/admin/users] from:127.0.0.1 costs:37.600 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:15:20,802 DEBUG 98172   ---  [MainThread] - [GET] -> [/cms/admin/authority] from:127.0.0.1 costs:12.820 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:15:21,123 DEBUG 98172   ---  [MainThread] - [DELETE] -> [/cms/admin/6] from:127.0.0.1 costs:12.500 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:15:21,183 DEBUG 98172   ---  [MainThread] - [GET] -> [/cms/admin/users] from:127.0.0.1 costs:14.230 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:39:13,051 DEBUG 98616   ---  [MainThread] - [GET] -> [/cms/admin/authority] from:127.0.0.1 costs:12.670 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:39:13,369 DEBUG 98616   ---  [MainThread] - [DELETE] -> [/cms/admin/6] from:127.0.0.1 costs:15.760 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:39:13,417 DEBUG 98616   ---  [MainThread] - [GET] -> [/cms/admin/users] from:127.0.0.1 costs:8.830 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:48:25,913 ERROR 99079   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 281, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'OrderProduct' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/theme.py", line 14, in get
    model = Theme.get_model(tid, err_msg='相关主题不存在或已经隐藏')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 29, in get_model
    model = cls.query.filter_by(id=id, delete_time=None).first()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 512, in __get__
    mapper = orm.class_mapper(type)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 421, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 400, in _inspect_mapped_class
    mapper._configure_all()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1276, in _configure_all
    configure_mappers()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 3033, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1832, in _post_configure_properties
    prop.init()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/interfaces.py", line 183, in init
    self.do_init()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 1655, in do_init
    self._process_dependent_arguments()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 1712, in _process_dependent_arguments
    self.target = self.mapper.mapped_table
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 767, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 1628, in mapper
    argument = self.argument()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 293, in __call__
    (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|Product|product, expression 'OrderProduct' failed to locate a name ("name 'OrderProduct' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.models.product.Product'> class after both dependent classes have been defined.

2019-11-12 11:48:34,691 DEBUG 99079   ---  [MainThread] - [GET] -> [/cms/theme/get/1] from:127.0.0.1 costs:15690.550 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 11:50:03,003 ERROR 99146   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 281, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'ProductProperty' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/theme.py", line 14, in get
    model = Theme.get_model(tid, err_msg='相关主题不存在或已经隐藏')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 29, in get_model
    model = cls.query.filter_by(id=id, delete_time=None).first()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 512, in __get__
    mapper = orm.class_mapper(type)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 421, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 400, in _inspect_mapped_class
    mapper._configure_all()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1276, in _configure_all
    configure_mappers()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 3033, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1832, in _post_configure_properties
    prop.init()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/interfaces.py", line 183, in init
    self.do_init()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 1655, in do_init
    self._process_dependent_arguments()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 1712, in _process_dependent_arguments
    self.target = self.mapper.mapped_table
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 767, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 1628, in mapper
    argument = self.argument()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 293, in __call__
    (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|Product|product, expression 'ProductProperty' failed to locate a name ("name 'ProductProperty' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.models.product.Product'> class after both dependent classes have been defined.

2019-11-12 11:50:03,013 DEBUG 99146   ---  [MainThread] - [GET] -> [/cms/theme/get/1] from:127.0.0.1 costs:125.120 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 21:42:13,238 DEBUG 99791   ---  [MainThread] - [GET] -> [/cms/theme/get/1] from:127.0.0.1 costs:95.370 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 21:44:06,362 DEBUG 99822   ---  [MainThread] - [GET] -> [/cms/theme/get/1] from:127.0.0.1 costs:7514.780 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 21:51:20,333 DEBUG 99870   ---  [MainThread] - [GET] -> [/cms/theme/get/1] from:127.0.0.1 costs:57.440 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 21:51:20,695 DEBUG 99870   ---  [MainThread] - [GET] -> [/cms/theme/get/all] from:127.0.0.1 costs:29.650 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 22:07:20,586 DEBUG 271   ---  [MainThread] - [GET] -> [/cms/theme/1] from:127.0.0.1 costs:56.840 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 22:07:20,930 DEBUG 271   ---  [MainThread] - [GET] -> [/cms/theme/all] from:127.0.0.1 costs:40.520 ms data:{
	param: {}, 
	body: {}
} 
2019-11-12 22:08:08,240 ERROR 271   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
cymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`snack`.`theme`, CONSTRAINT `theme_ibfk_1` FOREIGN KEY (`topic_img_id`) REFERENCES `image` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/theme.py", line 27, in create
    Theme.add_model(form.data, err_msg='主题已经存在或已经隐藏')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 170, in add_model
    cls.create(**data, commit=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/interface.py", line 149, in create
    db.session.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (cymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`snack`.`theme`, CONSTRAINT `theme_ibfk_1` FOREIGN KEY (`topic_img_id`) REFERENCES `image` (`id`))') [SQL: 'INSERT INTO theme (create_time, update_time, delete_time, name, description, topic_img_id, head_img_id) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2019, 11, 12, 22, 7, 24, 833205), datetime.datetime(2019, 11, 12, 22, 7, 24, 833260), None, '美味水果世界', '美味水果世界, 多汁多甜多嫩', 1, 1)] (Background on this error at: http://sqlalche.me/e/gkpj)

2019-11-12 22:08:08,244 DEBUG 271   ---  [MainThread] - [POST] -> [/cms/theme] from:127.0.0.1 costs:47255.520 ms data:{
	param: {}, 
	body: {'description': '美味水果世界, 多汁多甜多嫩', 'head_img_id': 1, 'name': '美味水果世界', 'topic_img_id': 1}
} 
